config/routes.rb
Smuseumapp::Application.routes.draw do
  resources :museums

  root :to => "pages#index"

  get "pages/index"

  get "pages/contact"
  
  match "/contact", :to => "pages#contact"

end

app/models/museum.rb
class Museum < ActiveRecord::Base
  attr_accessible :name, :website, :address, :city, :state, :zip_code, :free_days, :hours

  validates_length_of :name,  
                        :within => 5..80,
                        :too_long => "should be shorter.",
                        :too_short => "should be longer." 
  validates_format_of :website, :with => /^(#{URI::regexp(%w(http https))})$/, :allow_blank => false
  validates_length_of :address, 
                        :within => 8..150,
                        :too_long => "should be shorter.",
                        :too_short => "should be longer."
  validates_length_of :city,
                        :within => 5..150,
                        :too_long => "should be shorter.",
                        :too_short => "should be longer."
  validates :hours,     :presence => true
  validates :state,     :presence => true                          
  validates :zip_code,  :presence => true
  validates :free_days, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/museums_controller.rb
class MuseumsController < ApplicationController
  # GET /museums
  # GET /museums.xml
  def index
    @museums = Museum.all
    @title = "Listing All Museums"

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @museums }
    end
  end

  # GET /museums/1
  # GET /museums/1.xml
  def show
    @museum = Museum.find(params[:id])
    @title = "#{@museum.name} Information"

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @museum }
    end
  end

  # GET /museums/new
  # GET /museums/new.xml
  def new
    @museum = Museum.new
    @title = "New Museum"

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @museum }
    end
  end

  # GET /museums/1/edit
  def edit
    @museum = Museum.find(params[:id])
    @title = "Editing #{@museum.name} Information"
  end

  # POST /museums
  # POST /museums.xml
  def create
    @museum = Museum.new(params[:museum])
    @title = "#{@museum.name} Created"

    respond_to do |format|
      if @museum.save
        format.html { redirect_to(@museum, :notice => 'Museum was successfully created.') }
        format.xml  { render :xml => @museum, :status => :created, :location => @museum }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @museum.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /museums/1
  # PUT /museums/1.xml
  def update
    @museum = Museum.find(params[:id])

    respond_to do |format|
      if @museum.update_attributes(params[:museum])
        format.html { redirect_to(@museum, :notice => 'Museum was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @museum.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /museums/1
  # DELETE /museums/1.xml
  def destroy
    @museum = Museum.find(params[:id])
    @title = "#{@museum.name} Destroyed"
    @museum.destroy

    respond_to do |format|
      format.html { redirect_to(museums_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # GET /museums
  # GET /museums.xml

  @today_pretty = Time.now.strftime("%A, %B %d, %Y") 
  @today_useful = Time.now.strftime("%m/%d/%Y")

  def index
    @title = "Home"
    @museums = Museum.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @museums }
    end
  end

  def contact
    @title = "Contact"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Return a title on a per-page basis.
  def title
    base_title = "Free Museums Today"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/museums_helper.rb
module MuseumsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-20955443-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/_css.html.erb
  <%= stylesheet_link_tag :all %>
  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->    
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
  <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
  <%= stylesheet_link_tag 'custom', :media => 'screen' %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= render 'layouts/css' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <link rel="shortcut icon" href="/images/favicon.ico" />
  <%= render 'layouts/analytics' %>
</head>
<body>
  <div class="container">
    <div class="span-12">
      <header class="round">
        <h1><%= link_to "Free Museums Today", root_path, :class => "clearlink header" %></h1>
      </header>
    </div>
    <div class="span-5 last right">
      <nav class="round">
        <ul>
          <li><%= link_to "Share on Twitter", "http://twitter.com/home?status=Find free museums in Chicago on http://freemuseumstoday.com!", :title => "Click to share on Twitter", :class => "round", :target => "_blank" %></li>
          <li><%= link_to "Share on Facebook", "http://www.facebook.com/sharer.php?u=http://freemuseumstoday.com&t=Free Museums Today", :title => "Click to share on Facebook", :class => "round", :target => "_blank" %></li>
          <li><%= link_to "Contact", contact_path, :class => "round" %></li>
        </ul>
      </nav>
    </div>
    <section class="clear round">
      <%= yield %>
    </section>
    <footer>
      <nav class="round">
        &copy; 2011 Ian
      </nav>
    </footer>
  </div>
</body>
</html>

app/views/museums/_form.html.erb
<% @time = Time.now %>
<% @today = @time.strftime("%m/%d/%Y") %>
<% @tomorrow = @time + 1.days %>
<% @tomorrow = @tomorrow.strftime("%m/%d/%Y") %>
<% @yesterday = @time - 1.days %>
<% @yesterday = @yesterday.strftime("%m/%d/%Y") %>
<%= form_for(@museum) do |f| %>
  <% if @museum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@museum.errors.count, "error") %> prohibited this museum from being saved:</h2>

      <ul>
      <% @museum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="span-4"><%= f.label :name %></div>
    <div class="span-13 last"><%= f.text_field :name %></div>
  </div>
  <hr class="space" />
  <div class="field">
    <div class="span-4"><%= f.label :address %></div>
    <div class="span-13 last"><%= f.text_field :address %></div>
  </div>
  <hr class="space" />
  <div class="field">
    <div class="span-4"><%= f.label :city %></div>
    <div class="span-13 last"><%= f.text_field :city %></div>
  </div>
  <hr class="space" />
  <div class="field">
    <div class="span-4"><%= f.label :state %></div>
    <div class="span-13 last"><%= f.text_field :state %></div>
  </div>
  <hr class="space" />
  <div class="field">
    <div class="span-4"><%= f.label :zip_code %></div>
    <div class="span-13 last"><%= f.text_field :zip_code %></div>
  </div>   
  <hr class="space" />
  <div class="field">
    <div class="span-4"><%= f.label :website %></div>
    <div class="span-13 last"><%= f.text_field :website %></div>
  </div> 
  <hr class="space" />
  <div class="field">
    <div class="span-4"><%= f.label :hours %></div>
    <div class="span-13 last"><%= f.text_field :hours %></div>
  </div>
  <hr class="space" />
  <div class="field">
    <div class="span-4"><%= f.label :free_days %><br />
      <span class="quiet small"><%= f.label "Please format Free days as MM/DD/YYYY (#{@today}) and separate dates with spaces as follows: #{@yesterday} #{@today} #{@tomorrow}" %>
    </div></span>
    <div class="span-13 last"><%= f.text_area :free_days %></div>
  </div>
  <hr class="space" />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/museums/edit.html.erb
<h1>Editing museum</h1>

<%= render 'form' %>

<%= link_to 'Show', @museum %> |
<%= link_to 'Back', museums_path %>

app/views/museums/index.html.erb
<hr class="space" />
<p>
  <%= link_to 'New Museum', new_museum_path, :class => "button round new_museum" %>
</p>

<% @museums.each do |museum| %>
  <div class="museum round span-17 last">
    <div class="span-11"><h3><%= museum.name %></h3></div>
    <div class="span-6 right last">
      <%= link_to "View", museum, :class => "button round modify_museum" %>
      <%= link_to "Edit", edit_museum_path(museum), :class => "button round modify_museum" %>                         
      <%= link_to "Delete", museum, :class => "button round modify_museum", :confirm => 'Are you sure?', :method => :delete %>
    </div>
    <div class="span-3 bold clear"> Website: </div>
    <div class="span-14 last"> <%= link_to museum.website, museum.website, :class => "clearlink" %> </div> 
    <div class="span-3 bold"> Address: </div> 
    <div class="span-14 last"> <%= museum.address %> </div>
    <div class="span-3 bold"> City: </div>
    <div class="span-14 last"> <%= museum.city %> </div>
    <div class="span-3 bold"> State: </div>
    <div class="span-14 last"> <%= museum.state %> </div> 
    <div class="span-3 bold"> Zipcode: </div>
    <div class="span-14 last"> <%= museum.zip_code %> </div>
    <div class="span-3 bold"> Hours: </div>
    <div class="span-14 last"> 
      <% @hours = museum.hours.to_s.split(', ') %> 
      <% @hours.each do |hour| %>
        <%= hour %><br />
      <% end %>
    </div>
    <div class="span-3 bold"> Free Days: </div>
    <div class="span-14 last"> <%= museum.free_days %> </div>
  </div>
<% end %>

<hr class="space" />

<p>
  <%= link_to 'New Museum', new_museum_path, :class => "add_museum_button round" %>
</p>

app/views/museums/new.html.erb
<h1>New museum</h1>

<%= render 'form' %>

<%= link_to 'Back', museums_path %>

app/views/museums/show.html.erb
<p id="notice"><%= notice %></p>

  <div class="museum round span-17 last">
    <div class="span-11"><h3><%= @museum.name %></h3></div>
    <div class="span-6 right last">
      <%= link_to "Edit", edit_museum_path(@museum), :class => "button round" %>                         
      <%= link_to "Delete", @museum, :class => "button round", :confirm => 'Are you sure?', :method => :delete %>
    </div>
    <div class="span-3 bold clear"> Website: </div>
    <div class="span-14 last"> <%= link_to @museum.website, @museum.website %> </div> 
    <div class="span-3 bold"> Address: </div> 
    <div class="span-14 last"> <%= @museum.address %> </div>
    <div class="span-3 bold"> City: </div>
    <div class="span-14 last"> <%= @museum.city %> </div>
    <div class="span-3 bold"> State: </div>
    <div class="span-14 last"> <%= @museum.state %> </div> 
    <div class="span-3 bold"> Zipcode: </div>
    <div class="span-14 last"> <%= @museum.zip_code %> </div>
    <div class="span-3 bold"> Hours: </div>
    <div class="span-14 last">
      <% @hours = @museum.hours.to_s.split(', ') %> 
      <% @hours.each do |hour| %>
        <%= hour %><br />
      <% end %>
    </div>
    <div class="span-3 bold"> Free Days: </div>
    <div class="span-14 last"> <%= @museum.free_days %> </div>
  </div> 

<%= link_to 'Back', museums_path %>

app/views/pages/_find.html.erb
<% @today = Time.now.strftime("%m/%d/%Y") %>
<% @free_museums = [] %> 
<% @not_free = [] %>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>FreeMuseumsToday.com is still very much in development.</p>
<p>If you have any feedback or questions please send me an email, I would love to hear from you!</p>
<p>All email can be directed to <%= mail_to "ian@freemuseumstoday.com", "ian@freemuseumstoday.com", :subject => "Regarding Free Museums Today" %>.</p>

app/views/pages/index.html.erb
<% @future_date = "" %>
<h1>Today is <%= Time.now.strftime("%A, %B %d, %Y") %></h1>

<% @today = Time.now.strftime("%m/%d/%Y")
  @free_museums = [] 
  @is_free = [] 
  @not_free = [] %>

<% @museums.each do |m|
   @free_days = []
   @free_days = m[:free_days].split(' ')
   @free_days.each do |fd|
     if @today == fd 
       @is_free << m.id.to_s 
     else
     end
   end
end %>

<% @city = []
@museums.each do |m|
  @city << m.city
end %>

<% @museums.each do |m|
  if @is_free.include?(m.id.to_s) && m.city.to_s.include?("Chicago")
     @addr = "#{m.address}, #{m.city}, #{m.state} #{m.zip_code.to_s}" %>

    <div class="museum round span-17 last">
      <h3><%= link_to m.name, m.website, :class => "clearlink" %> is free today.</h3> 
      <div class="span-4 bold">
        Address:
      </div>
      <div class="span-13 last">
          <%= m.address %><br /><%= m.city + ', ' + m.state + ' ' + m.zip_code.to_s %>
      </div>
      <div class="span-4 bold">
          Get Directions:
      </div>
      <div class="span-13 last">
        <form action="http://maps.google.com/maps" method="get" target="_blank">
          Enter your address: 
          <input type="text" name="saddr" class="get_directions_field" />
          <input type="hidden" name="daddr" value="<%= @addr %>" />
          <input type="submit" value="Get Directions" class="button round get_directions" />
        </form>                                             
    </div>     
    <div class="span-4 bold">
      Hours:
    </div>
    <div class="span-13 last">
      <% @hours = m.hours.to_s.split(', ') %> 
        <% @hours.each do |hour| %>
          <%= hour %><br />
        <% end %>      
      </ul>
    </div>                                   
    <div class="span-17 last right">
      <%= mail_to("ian@freemuseumstoday.com", "Report Error", :subject => "I found a problem with #{m.name}", :class => "button round report_error") %>
    </div>
  </div>

  <% else
  @not_free << m.id.to_s
   end
end %>

<% @museums.each do |m|
  if @not_free.include?(m.id.to_s) %>
    <div class="museum round span-17 last">
      <%= link_to m.name, m.website %> is not free today.
    </div>
<% else
  end
end %>

<hr class="space" />   